namespace EventViewerX;

/// <summary>Built-in projector registration that does not require runtime type discovery.</summary>
public static partial class EventTypeCatalog {
    private static bool _builtInRulesRegistered;

    /// <summary>
    /// Registers every built-in typed event projector through strongly referenced delegates.
    /// Call this before <see cref="Configure(EventRuleDiscoveryMode)"/> and select
    /// <see cref="EventRuleDiscoveryMode.ExplicitOnly"/> in trimmed or NativeAOT hosts.
    /// </summary>
    public static void RegisterBuiltInRules() {
        lock (_initLock) {
            if (_initialized) {
                throw new InvalidOperationException(
                    "Built-in rules must be registered before the first event-type query.");
            }
            if (_builtInRulesRegistered) {
                return;
            }

            RegisterBuiltInRuleFactories();
            _builtInRulesRegistered = true;
        }
    }

    private static void RegisterBuiltInRuleFactories() {
        RegisterRuleFactory(EventType.AADConnectRunProfile, "Application", new[] { 906 }, new[] { "Directory Synchronization" }, static source => new global::EventViewerX.Rules.AADConnect.AADConnectRunProfile(source), ruleType: typeof(global::EventViewerX.Rules.AADConnect.AADConnectRunProfile));
        RegisterRuleFactory(EventType.ADComputerChangeDetailed, "Security", new[] { 5136, 5137, 5139, 5141 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADComputerChangeDetailed(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADComputerChangeDetailed));
        RegisterRuleFactory(EventType.ADComputerCreateChange, "Security", new[] { 4741, 4742 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADComputerCreateChange(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADComputerCreateChange));
        RegisterRuleFactory(EventType.ADComputerDeleted, "Security", new[] { 4743 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADComputerDeleted(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADComputerDeleted));
        RegisterRuleFactory(EventType.ADGroupChange, "Security", new[] { 4735, 4737, 4745, 4750, 4760, 4764, 4784, 4791 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADGroupChange(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADGroupChange));
        RegisterRuleFactory(EventType.ADGroupChangeDetailed, "Security", new[] { 5136, 5137, 5139, 5141 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADGroupChangeDetailed(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADGroupChangeDetailed));
        RegisterRuleFactory(EventType.ADGroupCreateDelete, "Security", new[] { 4727, 4730, 4731, 4734, 4744, 4748, 4749, 4753, 4754, 4758, 4759, 4763 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADGroupCreateDelete(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADGroupCreateDelete));
        RegisterRuleFactory(EventType.ADGroupEnumeration, "Security", new[] { 4798, 4799 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADGroupEnumeration(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADGroupEnumeration));
        RegisterRuleFactory(EventType.ADGroupMembershipChange, "Security", new[] { 4728, 4729, 4732, 4733, 4746, 4747, 4751, 4752, 4756, 4757, 4761, 4762, 4785, 4786, 4787, 4788 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADGroupMembershipChange(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADGroupMembershipChange));
        RegisterRuleFactory(EventType.ADGroupPolicyChanges, "Security", new[] { 5136, 5137, 5141 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADGroupPolicyChanges(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADGroupPolicyChanges));
        RegisterRuleFactory(EventType.ADGroupPolicyChangesDetailed, "Security", new[] { 5136, 5137, 5139, 5141 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADGroupPolicyChangesDetailed(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADGroupPolicyChangesDetailed), matchPriority: 100);
        RegisterRuleFactory(EventType.ADGroupPolicyEdits, "Security", new[] { 5136, 5137, 5141 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADGroupPolicyEdits(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADGroupPolicyEdits), matchPriority: 300);
        RegisterRuleFactory(EventType.ADGroupPolicyLinks, "Security", new[] { 5136, 5137, 5141 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADGroupPolicyLinks(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADGroupPolicyLinks), matchPriority: 300);
        RegisterRuleFactory(EventType.ADLdapBindingDetails, "Directory Service", new[] { 2889 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADLdapBindingDetails(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADLdapBindingDetails));
        RegisterRuleFactory(EventType.ADLdapBindingSummary, "Directory Service", new[] { 2887 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADLdapBindingSummary(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADLdapBindingSummary));
        RegisterRuleFactory(EventType.ADOrganizationalUnitChangeDetailed, "Security", new[] { 5136, 5137, 5139, 5141 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADOrganizationalUnitChangeDetailed(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADOrganizationalUnitChangeDetailed));
        RegisterRuleFactory(EventType.ADOtherChangeDetailed, "Security", new[] { 5136, 5137, 5139, 5141 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADOtherChangeDetailed(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADOtherChangeDetailed), matchPriority: -100);
        RegisterRuleFactory(EventType.ADUserChangeDetailed, "Security", new[] { 5136, 5137, 5139, 5141 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADUserChangeDetailed(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADUserChangeDetailed));
        RegisterRuleFactory(EventType.ADUserCreateChange, "Security", new[] { 4720, 4738 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADUserCreateChange(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADUserCreateChange));
        RegisterRuleFactory(EventType.ADUserLockouts, "Security", new[] { 4740 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADUserLockouts(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADUserLockouts));
        RegisterRuleFactory(EventType.ADUserLogon, "Security", new[] { 4624 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADUserLogon(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADUserLogon));
        RegisterRuleFactory(EventType.ADUserLogonFailed, "Security", new[] { 4625 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADUserLogonFailed(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADUserLogonFailed));
        RegisterRuleFactory(EventType.ADUserLogonNTLMv1, "Security", new[] { 4624 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADUserLogonNTLMv1(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADUserLogonNTLMv1), matchPriority: 200);
        RegisterRuleFactory(EventType.ADUserPrivilegeUse, "Security", new[] { 4672 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADUserPrivilegeUse(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADUserPrivilegeUse));
        RegisterRuleFactory(EventType.ADUserRightsAssignment, "Security", new[] { 4704, 4705 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADUserRightsAssignment(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADUserRightsAssignment));
        RegisterRuleFactory(EventType.ADUserStatus, "Security", new[] { 4722, 4725, 4723, 4724, 4726 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADUserStatus(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADUserStatus));
        RegisterRuleFactory(EventType.ADUserUnlocked, "Security", new[] { 4767 }, static source => new global::EventViewerX.Rules.ActiveDirectory.ADUserUnlocked(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.ADUserUnlocked));
        RegisterRuleFactory(EventType.GpoCreated, "Security", new[] { 5137 }, static source => new global::EventViewerX.Rules.ActiveDirectory.GpoCreated(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.GpoCreated), matchPriority: 250);
        RegisterRuleFactory(EventType.GpoDeleted, "Security", new[] { 5141 }, static source => new global::EventViewerX.Rules.ActiveDirectory.GpoDeleted(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.GpoDeleted), matchPriority: 250);
        RegisterRuleFactory(EventType.GpoModified, "Security", new[] { 5136 }, static source => new global::EventViewerX.Rules.ActiveDirectory.GpoModified(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.GpoModified), matchPriority: 250);
        RegisterRuleFactory(EventType.GroupPolicyDirectoryAudit, "Security", new[] { 5136, 5137, 5139, 5141 }, static source => new global::EventViewerX.Rules.ActiveDirectory.GroupPolicyDirectoryAudit(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.GroupPolicyDirectoryAudit));
        RegisterRuleFactory(EventType.AADConnectPasswordSyncFailed, "Application", new[] { 611 }, new[] { "Directory Synchronization" }, static source => new global::EventViewerX.Rules.ActiveDirectory.PasswordSyncFailed(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.PasswordSyncFailed));
        RegisterRuleFactory(EventType.ADSMBServerAuditV1, "Microsoft-Windows-SMBServer/Audit", new[] { 3000 }, static source => new global::EventViewerX.Rules.ActiveDirectory.SMBServerAudit(source), ruleType: typeof(global::EventViewerX.Rules.ActiveDirectory.SMBServerAudit));
        RegisterRuleFactory(EventType.AADConnectStagingDisabled, "Application", new[] { 351 }, new[] { "Directory Synchronization" }, static source => new global::EventViewerX.Rules.AzureAD.AADConnectStagingDisabled(source), ruleType: typeof(global::EventViewerX.Rules.AzureAD.AADConnectStagingDisabled));
        RegisterRuleFactory(EventType.AADConnectStagingEnabled, "Application", new[] { 350 }, new[] { "Directory Synchronization" }, static source => new global::EventViewerX.Rules.AzureAD.AADConnectStagingEnabled(source), ruleType: typeof(global::EventViewerX.Rules.AzureAD.AADConnectStagingEnabled));
        RegisterRuleFactory(EventType.AADSyncCycleStage, "Application", new[] { 904 }, new[] { "Directory Synchronization" }, static source => new global::EventViewerX.Rules.AzureAD.AADSyncCycleStage(source), ruleType: typeof(global::EventViewerX.Rules.AzureAD.AADSyncCycleStage));
        RegisterRuleFactory(EventType.AADSyncFilterStatus, "Application", new[] { 6952 }, new[] { "ADSync" }, static source => new global::EventViewerX.Rules.AzureAD.AADSyncFilterStatus(source), ruleType: typeof(global::EventViewerX.Rules.AzureAD.AADSyncFilterStatus));
        RegisterRuleFactory(EventType.AADSyncImportStatus, "Application", new[] { 105, 132, 133, 134 }, new[] { "Directory Synchronization" }, static source => new global::EventViewerX.Rules.AzureAD.AADSyncImportStatus(source), ruleType: typeof(global::EventViewerX.Rules.AzureAD.AADSyncImportStatus));
        RegisterRuleFactory(EventType.AADSyncPasswordHashSyncStatus, "Application", new[] { 663 }, new[] { "Directory Synchronization" }, static source => new global::EventViewerX.Rules.AzureAD.AADSyncPasswordHashSyncStatus(source), ruleType: typeof(global::EventViewerX.Rules.AzureAD.AADSyncPasswordHashSyncStatus));
        RegisterRuleFactory(EventType.AADSyncProvisionCredentialsPing, "Application", new[] { 653, 654 }, new[] { "Directory Synchronization" }, static source => new global::EventViewerX.Rules.AzureAD.AADSyncProvisionCredentialsPing(source), ruleType: typeof(global::EventViewerX.Rules.AzureAD.AADSyncProvisionCredentialsPing));
        RegisterRuleFactory(EventType.CertificateIssued, "Security", new[] { 4886, 4887 }, static source => new global::EventViewerX.Rules.CertificateAuthority.CertificateIssued(source), ruleType: typeof(global::EventViewerX.Rules.CertificateAuthority.CertificateIssued));
        RegisterRuleFactory(EventType.DhcpLeaseCreated, "Microsoft-Windows-DHCP Server/Operational", new[] { 10 }, static source => new global::EventViewerX.Rules.DHCP.DhcpLeaseCreated(source), ruleType: typeof(global::EventViewerX.Rules.DHCP.DhcpLeaseCreated));
        RegisterRuleFactory(EventType.ExchangeDatabaseMounted, "Application", new[] { 9526 }, static source => new global::EventViewerX.Rules.Exchange.ExchangeDatabaseMounted(source), ruleType: typeof(global::EventViewerX.Rules.Exchange.ExchangeDatabaseMounted));
        RegisterRuleFactory(EventType.HyperVVirtualMachineStarted, "Microsoft-Windows-Hyper-V-VMMS/Admin", new[] { 18500 }, static source => new global::EventViewerX.Rules.HyperV.HyperVVirtualMachineStarted(source), ruleType: typeof(global::EventViewerX.Rules.HyperV.HyperVVirtualMachineStarted));
        RegisterRuleFactory(EventType.HyperVCheckpointCreated, "Microsoft-Windows-Hyper-V-VMMS/Admin", new[] { 4096 }, static source => new global::EventViewerX.Rules.HyperV.VmCheckpointCreated(source), ruleType: typeof(global::EventViewerX.Rules.HyperV.VmCheckpointCreated));
        RegisterRuleFactory(EventType.HyperVVirtualMachineShutdown, "Microsoft-Windows-Hyper-V-Worker/Operational", new[] { 18560 }, static source => new global::EventViewerX.Rules.HyperV.VmShutdown(source), ruleType: typeof(global::EventViewerX.Rules.HyperV.VmShutdown));
        RegisterRuleFactory(EventType.IISSiteBindingFailure, "System", new[] { 1007 }, static source => new global::EventViewerX.Rules.IIS.IISSiteBindingFailure(source), ruleType: typeof(global::EventViewerX.Rules.IIS.IISSiteBindingFailure));
        RegisterRuleFactory(EventType.IISSiteStopped, "System", new[] { 1005 }, static source => new global::EventViewerX.Rules.IIS.IISSiteStopped(source), ruleType: typeof(global::EventViewerX.Rules.IIS.IISSiteStopped));
        RegisterRuleFactory(EventType.KerberosPolicyChange, "Security", new[] { 4713 }, static source => new global::EventViewerX.Rules.Kerberos.KerberosPolicyChange(source), ruleType: typeof(global::EventViewerX.Rules.Kerberos.KerberosPolicyChange));
        RegisterRuleFactory(EventType.KerberosKdcRc4Audit, "System", new[] { 201, 202, 203, 204, 205, 206, 207, 208, 209 }, new[] { "Kdcsvc" }, static source => new global::EventViewerX.Rules.Kerberos.KerberosKdcRc4Audit(source), canHandle: static source => global::EventViewerX.Rules.RuleHelpers.IsProvider(source, "Kdcsvc"), ruleType: typeof(global::EventViewerX.Rules.Kerberos.KerberosKdcRc4Audit));
        RegisterRuleFactory(EventType.KerberosServiceTicket, "Security", new[] { 4769, 4770 }, static source => new global::EventViewerX.Rules.Kerberos.KerberosServiceTicket(source), ruleType: typeof(global::EventViewerX.Rules.Kerberos.KerberosServiceTicket));
        RegisterRuleFactory(EventType.KerberosTGTRequest, "Security", new[] { 4768 }, static source => new global::EventViewerX.Rules.Kerberos.KerberosTGTRequest(source), ruleType: typeof(global::EventViewerX.Rules.Kerberos.KerberosTGTRequest));
        RegisterRuleFactory(EventType.KerberosTicketFailure, "Security", new[] { 4771, 4772 }, static source => new global::EventViewerX.Rules.Kerberos.KerberosTicketFailure(source), ruleType: typeof(global::EventViewerX.Rules.Kerberos.KerberosTicketFailure));
        RegisterRuleFactory(EventType.LogsClearedOther, "System", new[] { 104 }, static source => new global::EventViewerX.Rules.Logging.LogsClearedOther(source), ruleType: typeof(global::EventViewerX.Rules.Logging.LogsClearedOther));
        RegisterRuleFactory(EventType.LogsClearedSecurity, "Security", new[] { 1102, 1105 }, static source => new global::EventViewerX.Rules.Logging.LogsClearedSecurity(source), ruleType: typeof(global::EventViewerX.Rules.Logging.LogsClearedSecurity));
        RegisterRuleFactory(EventType.LogsFullSecurity, "Security", new[] { 1104 }, static source => new global::EventViewerX.Rules.Logging.LogsFullSecurity(source), ruleType: typeof(global::EventViewerX.Rules.Logging.LogsFullSecurity));
        RegisterRuleFactory(EventType.NetworkAccessAuthenticationPolicy, "Security", new[] { 6272, 6273 }, static source => new global::EventViewerX.Rules.NPS.NetworkAccessAuthenticationPolicy(source), ruleType: typeof(global::EventViewerX.Rules.NPS.NetworkAccessAuthenticationPolicy));
        RegisterRuleFactory(EventType.SqlDatabaseCreated, "Application", new[] { 17137, 1802 }, static source => new global::EventViewerX.Rules.SQL.SqlDatabaseCreated(source), ruleType: typeof(global::EventViewerX.Rules.SQL.SqlDatabaseCreated));
        RegisterRuleFactory(EventType.AuditPolicyChange, "Security", new[] { 4719 }, static source => new global::EventViewerX.Rules.Windows.AuditPolicyChange(source), ruleType: typeof(global::EventViewerX.Rules.Windows.AuditPolicyChange));
        RegisterRuleFactory(EventType.BitLockerKeyChange, "Security", new[] { 4673, 4692 }, static source => new global::EventViewerX.Rules.Windows.BitLockerKeyChange(source), ruleType: typeof(global::EventViewerX.Rules.Windows.BitLockerKeyChange));
        RegisterRuleFactory(EventType.BitLockerSuspended, "BitLocker-API", new[] { 24660 }, static source => new global::EventViewerX.Rules.Windows.BitLockerSuspended(source), ruleType: typeof(global::EventViewerX.Rules.Windows.BitLockerSuspended));
        RegisterRuleFactory(EventType.ClientGroupPoliciesApplication, "Application", new[] { 4098 }, static source => new global::EventViewerX.Rules.Windows.ClientGroupPoliciesApplication(source), ruleType: typeof(global::EventViewerX.Rules.Windows.ClientGroupPoliciesApplication));
        RegisterRuleFactory(EventType.ClientGroupPoliciesSystem, "System", new[] { 1085 }, static source => new global::EventViewerX.Rules.Windows.ClientGroupPoliciesSystem(source), ruleType: typeof(global::EventViewerX.Rules.Windows.ClientGroupPoliciesSystem));
        RegisterRuleFactory(EventType.DefenderConfigurationChanged, "Microsoft-Windows-Windows Defender/Operational", new[] { 5007 }, static source => new global::EventViewerX.Rules.Windows.DefenderConfigurationChanged(source), ruleType: typeof(global::EventViewerX.Rules.Windows.DefenderConfigurationChanged));
        RegisterRuleFactory(EventType.DefenderThreatAction, "Microsoft-Windows-Windows Defender/Operational", new[] { 1117 }, static source => new global::EventViewerX.Rules.Windows.DefenderThreatAction(source), ruleType: typeof(global::EventViewerX.Rules.Windows.DefenderThreatAction));
        RegisterRuleFactory(EventType.DefenderThreatDetected, "Microsoft-Windows-Windows Defender/Operational", new[] { 1116 }, static source => new global::EventViewerX.Rules.Windows.DefenderThreatDetected(source), ruleType: typeof(global::EventViewerX.Rules.Windows.DefenderThreatDetected));
        RegisterRuleFactory(EventType.DeviceDisabled, "Security", new[] { 6420 }, static source => new global::EventViewerX.Rules.Windows.DeviceDisabled(source), ruleType: typeof(global::EventViewerX.Rules.Windows.DeviceDisabled));
        RegisterRuleFactory(EventType.DeviceRecognized, "Security", new[] { 6416 }, static source => new global::EventViewerX.Rules.Windows.DeviceRecognized(source), ruleType: typeof(global::EventViewerX.Rules.Windows.DeviceRecognized));
        RegisterRuleFactory(EventType.DfsReplicationError, "DFS Replication", new[] { 5002 }, static source => new global::EventViewerX.Rules.Windows.DfsReplicationError(source), ruleType: typeof(global::EventViewerX.Rules.Windows.DfsReplicationError));
        RegisterRuleFactory(EventType.FirewallRuleAdded, "Security", new[] { 4946 }, static source => new global::EventViewerX.Rules.Windows.FirewallRuleAdded(source), ruleType: typeof(global::EventViewerX.Rules.Windows.FirewallRuleAdded));
        RegisterRuleFactory(EventType.FirewallRuleChange, "Security", new[] { 4947 }, static source => new global::EventViewerX.Rules.Windows.FirewallRuleChange(source), ruleType: typeof(global::EventViewerX.Rules.Windows.FirewallRuleChange));
        RegisterRuleFactory(EventType.FirewallRuleDeleted, "Security", new[] { 4948 }, static source => new global::EventViewerX.Rules.Windows.FirewallRuleDeleted(source), ruleType: typeof(global::EventViewerX.Rules.Windows.FirewallRuleDeleted));
        RegisterRuleFactory(EventType.NetworkMonitorDriverLoaded, "System", new[] { 6, 7035, 7045 }, static source => new global::EventViewerX.Rules.Windows.NetworkMonitorDriverLoaded(source), ruleType: typeof(global::EventViewerX.Rules.Windows.NetworkMonitorDriverLoaded));
        RegisterRuleFactory(EventType.NetworkPromiscuousMode, "System", new[] { 10400, 10401 }, static source => new global::EventViewerX.Rules.Windows.NetworkPromiscuousMode(source), ruleType: typeof(global::EventViewerX.Rules.Windows.NetworkPromiscuousMode));
        RegisterRuleFactory(EventType.ObjectDeletion, "Security", new[] { 4660 }, static source => new global::EventViewerX.Rules.Windows.ObjectDeletion(source), ruleType: typeof(global::EventViewerX.Rules.Windows.ObjectDeletion));
        RegisterRuleFactory(EventType.OSBugCheck, "System", new[] { 1001 }, static source => new global::EventViewerX.Rules.Windows.OSBugCheck(source), ruleType: typeof(global::EventViewerX.Rules.Windows.OSBugCheck));
        RegisterRuleFactory(EventType.OSCrash, "System", new[] { 6008 }, static source => new global::EventViewerX.Rules.Windows.OSCrash(source), ruleType: typeof(global::EventViewerX.Rules.Windows.OSCrash));
        RegisterRuleFactory(EventType.OSCrashOnAuditFailRecovery, "Security", new[] { 4621 }, static source => new global::EventViewerX.Rules.Windows.OSCrashOnAuditFailRecovery(source), ruleType: typeof(global::EventViewerX.Rules.Windows.OSCrashOnAuditFailRecovery));
        RegisterRuleFactory(EventType.OSShutdown, "System", new[] { 13 }, static source => new global::EventViewerX.Rules.Windows.OSShutdown(source), ruleType: typeof(global::EventViewerX.Rules.Windows.OSShutdown));
        RegisterRuleFactory(EventType.OSStartup, "System", new[] { 12 }, static source => new global::EventViewerX.Rules.Windows.OSStartup(source), ruleType: typeof(global::EventViewerX.Rules.Windows.OSStartup));
        RegisterRuleFactory(EventType.OSStartupSecurity, "Security", new[] { 4608 }, static source => new global::EventViewerX.Rules.Windows.OSStartupSecurity(source), ruleType: typeof(global::EventViewerX.Rules.Windows.OSStartupSecurity));
        RegisterRuleFactory(EventType.OSTimeChange, "Security", new[] { 4616 }, static source => new global::EventViewerX.Rules.Windows.OSTimeChange(source), ruleType: typeof(global::EventViewerX.Rules.Windows.OSTimeChange));
        RegisterRuleFactory(EventType.OSUncleanShutdown, "System", new[] { 41 }, static source => new global::EventViewerX.Rules.Windows.OSUncleanShutdown(source), ruleType: typeof(global::EventViewerX.Rules.Windows.OSUncleanShutdown));
        RegisterRuleFactory(EventType.ScheduledTaskCreated, "Security", new[] { 4698 }, static source => new global::EventViewerX.Rules.Windows.ScheduledTaskCreated(source), ruleType: typeof(global::EventViewerX.Rules.Windows.ScheduledTaskCreated));
        RegisterRuleFactory(EventType.ScheduledTaskDeleted, "Security", new[] { 4699 }, static source => new global::EventViewerX.Rules.Windows.ScheduledTaskDeleted(source), ruleType: typeof(global::EventViewerX.Rules.Windows.ScheduledTaskDeleted));
        RegisterRuleFactory(EventType.ScheduledTaskDisabled, "Security", new[] { 4701 }, static source => new global::EventViewerX.Rules.Windows.ScheduledTaskDisabled(source), ruleType: typeof(global::EventViewerX.Rules.Windows.ScheduledTaskDisabled));
        RegisterRuleFactory(EventType.ScheduledTaskEnabled, "Security", new[] { 4700 }, static source => new global::EventViewerX.Rules.Windows.ScheduledTaskEnabled(source), ruleType: typeof(global::EventViewerX.Rules.Windows.ScheduledTaskEnabled));
        RegisterRuleFactory(EventType.ScheduledTaskUpdated, "Security", new[] { 4702 }, static source => new global::EventViewerX.Rules.Windows.ScheduledTaskUpdated(source), ruleType: typeof(global::EventViewerX.Rules.Windows.ScheduledTaskUpdated));
        RegisterRuleFactory(EventType.SyncCompleted, "Application", new[] { 907 }, new[] { "Directory Synchronization" }, static source => new global::EventViewerX.Rules.Windows.SyncCompleted(source), ruleType: typeof(global::EventViewerX.Rules.Windows.SyncCompleted));
        RegisterRuleFactory(EventType.WindowsUpdateFailure, "Setup", new[] { 20 }, static source => new global::EventViewerX.Rules.Windows.WindowsUpdateFailure(source), ruleType: typeof(global::EventViewerX.Rules.Windows.WindowsUpdateFailure));
    }
}
